/**
 * Endpoints
 * Endpoints API for different services in SKIL
 *
 * The version of the OpenAPI document: 1.2.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Base64NDArrayBodyKNN model module.
 * @module ai/skymind/skil/model/Base64NDArrayBodyKNN
 * @version 1.2.2.0
 */
class Base64NDArrayBodyKNN {
    /**
     * Constructs a new <code>Base64NDArrayBodyKNN</code>.
     * @alias module:ai/skymind/skil/model/Base64NDArrayBodyKNN
     */
    constructor() { 
        
        Base64NDArrayBodyKNN.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Base64NDArrayBodyKNN</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:ai/skymind/skil/model/Base64NDArrayBodyKNN} obj Optional instance to populate.
     * @return {module:ai/skymind/skil/model/Base64NDArrayBodyKNN} The populated <code>Base64NDArrayBodyKNN</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Base64NDArrayBodyKNN();

            if (data.hasOwnProperty('ndarray')) {
                obj['ndarray'] = ApiClient.convertToType(data['ndarray'], 'String');
            }
            if (data.hasOwnProperty('k')) {
                obj['k'] = ApiClient.convertToType(data['k'], 'Number');
            }
            if (data.hasOwnProperty('forceFillK')) {
                obj['forceFillK'] = ApiClient.convertToType(data['forceFillK'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * the array to run the search on. Note that this must be a row vector
 * @member {String} ndarray
 */
Base64NDArrayBodyKNN.prototype['ndarray'] = undefined;

/**
 * the number of results to retrieve
 * @member {Number} k
 */
Base64NDArrayBodyKNN.prototype['k'] = undefined;

/**
 * If 'True' it will brute force search for running search relative to a target but forced to fill the result list until the desired k is matched.
 * @member {Boolean} forceFillK
 */
Base64NDArrayBodyKNN.prototype['forceFillK'] = undefined;






export default Base64NDArrayBodyKNN;

