/**
 * Endpoints
 * Endpoints API for different services in SKIL
 *
 * The version of the OpenAPI document: 1.2.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DetectedObject model module.
 * @module ai/skymind/skil/model/DetectedObject
 * @version 1.2.2.0
 */
class DetectedObject {
    /**
     * Constructs a new <code>DetectedObject</code>.
     * @alias module:ai/skymind/skil/model/DetectedObject
     */
    constructor() { 
        
        DetectedObject.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DetectedObject</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:ai/skymind/skil/model/DetectedObject} obj Optional instance to populate.
     * @return {module:ai/skymind/skil/model/DetectedObject} The populated <code>DetectedObject</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DetectedObject();

            if (data.hasOwnProperty('centerX')) {
                obj['centerX'] = ApiClient.convertToType(data['centerX'], 'Number');
            }
            if (data.hasOwnProperty('centerY')) {
                obj['centerY'] = ApiClient.convertToType(data['centerY'], 'Number');
            }
            if (data.hasOwnProperty('width')) {
                obj['width'] = ApiClient.convertToType(data['width'], 'Number');
            }
            if (data.hasOwnProperty('height')) {
                obj['height'] = ApiClient.convertToType(data['height'], 'Number');
            }
            if (data.hasOwnProperty('predictedClasses')) {
                obj['predictedClasses'] = ApiClient.convertToType(data['predictedClasses'], ['String']);
            }
            if (data.hasOwnProperty('confidences')) {
                obj['confidences'] = ApiClient.convertToType(data['confidences'], ['Number']);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} centerX
 */
DetectedObject.prototype['centerX'] = undefined;

/**
 * @member {Number} centerY
 */
DetectedObject.prototype['centerY'] = undefined;

/**
 * @member {Number} width
 */
DetectedObject.prototype['width'] = undefined;

/**
 * @member {Number} height
 */
DetectedObject.prototype['height'] = undefined;

/**
 * @member {Array.<String>} predictedClasses
 */
DetectedObject.prototype['predictedClasses'] = undefined;

/**
 * @member {Array.<Number>} confidences
 */
DetectedObject.prototype['confidences'] = undefined;






export default DetectedObject;

