/**
 * Endpoints
 * Endpoints API for different services in SKIL
 *
 * The version of the OpenAPI document: 1.2.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The FileUpload model module.
 * @module ai/skymind/skil/model/FileUpload
 * @version 1.2.2.0
 */
class FileUpload {
    /**
     * Constructs a new <code>FileUpload</code>.
     * @alias module:ai/skymind/skil/model/FileUpload
     */
    constructor() { 
        
        FileUpload.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>FileUpload</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:ai/skymind/skil/model/FileUpload} obj Optional instance to populate.
     * @return {module:ai/skymind/skil/model/FileUpload} The populated <code>FileUpload</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FileUpload();

            if (data.hasOwnProperty('key')) {
                obj['key'] = ApiClient.convertToType(data['key'], 'String');
            }
            if (data.hasOwnProperty('fileName')) {
                obj['fileName'] = ApiClient.convertToType(data['fileName'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('path')) {
                obj['path'] = ApiClient.convertToType(data['path'], 'String');
            }
            if (data.hasOwnProperty('fileContent')) {
                obj['fileContent'] = ApiClient.convertToType(data['fileContent'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} key
 */
FileUpload.prototype['key'] = undefined;

/**
 * @member {String} fileName
 */
FileUpload.prototype['fileName'] = undefined;

/**
 * @member {String} status
 */
FileUpload.prototype['status'] = undefined;

/**
 * @member {String} type
 */
FileUpload.prototype['type'] = undefined;

/**
 * @member {String} path
 */
FileUpload.prototype['path'] = undefined;

/**
 * @member {String} fileContent
 */
FileUpload.prototype['fileContent'] = undefined;






export default FileUpload;

