/**
 * Endpoints
 * Endpoints API for different services in SKIL
 *
 * The version of the OpenAPI document: 1.2.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GoogleStorageResourceDetails model module.
 * @module ai/skymind/skil/model/GoogleStorageResourceDetails
 * @version 1.2.2.0
 */
class GoogleStorageResourceDetails {
    /**
     * Constructs a new <code>GoogleStorageResourceDetails</code>.
     * @alias module:ai/skymind/skil/model/GoogleStorageResourceDetails
     */
    constructor() { 
        
        GoogleStorageResourceDetails.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GoogleStorageResourceDetails</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:ai/skymind/skil/model/GoogleStorageResourceDetails} obj Optional instance to populate.
     * @return {module:ai/skymind/skil/model/GoogleStorageResourceDetails} The populated <code>GoogleStorageResourceDetails</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GoogleStorageResourceDetails();

            if (data.hasOwnProperty('@class')) {
                obj['@class'] = ApiClient.convertToType(data['@class'], 'String');
            }
            if (data.hasOwnProperty('resourceId')) {
                obj['resourceId'] = ApiClient.convertToType(data['resourceId'], 'Number');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('subType')) {
                obj['subType'] = ApiClient.convertToType(data['subType'], 'String');
            }
            if (data.hasOwnProperty('projectId')) {
                obj['projectId'] = ApiClient.convertToType(data['projectId'], 'String');
            }
            if (data.hasOwnProperty('bucketName')) {
                obj['bucketName'] = ApiClient.convertToType(data['bucketName'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} @class
 * @default 'io.skymind.resource.model.subtypes.storage.GoogleStorageResourceDetails'
 */
GoogleStorageResourceDetails.prototype['@class'] = 'io.skymind.resource.model.subtypes.storage.GoogleStorageResourceDetails';

/**
 * ID of the resource
 * @member {Number} resourceId
 */
GoogleStorageResourceDetails.prototype['resourceId'] = undefined;

/**
 * Resource type
 * @member {module:ai/skymind/skil/model/GoogleStorageResourceDetails.TypeEnum} type
 */
GoogleStorageResourceDetails.prototype['type'] = undefined;

/**
 * Resource subtype
 * @member {module:ai/skymind/skil/model/GoogleStorageResourceDetails.SubTypeEnum} subType
 */
GoogleStorageResourceDetails.prototype['subType'] = undefined;

/**
 * Project ID
 * @member {String} projectId
 */
GoogleStorageResourceDetails.prototype['projectId'] = undefined;

/**
 * Name of the storage bucket
 * @member {String} bucketName
 */
GoogleStorageResourceDetails.prototype['bucketName'] = undefined;





/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
GoogleStorageResourceDetails['TypeEnum'] = {

    /**
     * value: "STORAGE"
     * @const
     */
    "STORAGE": "STORAGE"
};


/**
 * Allowed values for the <code>subType</code> property.
 * @enum {String}
 * @readonly
 */
GoogleStorageResourceDetails['SubTypeEnum'] = {

    /**
     * value: "GoogleStorage"
     * @const
     */
    "GoogleStorage": "GoogleStorage"
};



export default GoogleStorageResourceDetails;

