/**
 * Endpoints
 * Endpoints API for different services in SKIL
 *
 * The version of the OpenAPI document: 1.2.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The NearestNeighborsResult model module.
 * @module ai/skymind/skil/model/NearestNeighborsResult
 * @version 1.2.2.0
 */
class NearestNeighborsResult {
    /**
     * Constructs a new <code>NearestNeighborsResult</code>.
     * @alias module:ai/skymind/skil/model/NearestNeighborsResult
     */
    constructor() { 
        
        NearestNeighborsResult.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>NearestNeighborsResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:ai/skymind/skil/model/NearestNeighborsResult} obj Optional instance to populate.
     * @return {module:ai/skymind/skil/model/NearestNeighborsResult} The populated <code>NearestNeighborsResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NearestNeighborsResult();

            if (data.hasOwnProperty('index')) {
                obj['index'] = ApiClient.convertToType(data['index'], 'Number');
            }
            if (data.hasOwnProperty('distance')) {
                obj['distance'] = ApiClient.convertToType(data['distance'], 'Number');
            }
            if (data.hasOwnProperty('label')) {
                obj['label'] = ApiClient.convertToType(data['label'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} index
 */
NearestNeighborsResult.prototype['index'] = undefined;

/**
 * @member {Number} distance
 */
NearestNeighborsResult.prototype['distance'] = undefined;

/**
 * @member {String} label
 */
NearestNeighborsResult.prototype['label'] = undefined;






export default NearestNeighborsResult;

