=begin
#Endpoints

#Endpoints API for different services in SKIL

OpenAPI spec version: 1.2.0-rc1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SkilCient::UpdateBestModel
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'UpdateBestModel' do
  before do
    # run before each test
    @instance = SkilCient::UpdateBestModel.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of UpdateBestModel' do
    it 'should create an instance of UpdateBestModel' do
      expect(@instance).to be_instance_of(SkilCient::UpdateBestModel)
    end
  end
  describe 'test attribute "experiment_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "best_model_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
