# Endpoints
#
# Endpoints API for different services in SKIL
#
# OpenAPI spec version: 1.2.0-rc1
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' AddCredentialsRequest Class
#'
#' @field type 
#' @field name 
#' @field uri 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
AddCredentialsRequest <- R6::R6Class(
  'AddCredentialsRequest',
  public = list(
    `type` = NULL,
    `name` = NULL,
    `uri` = NULL,
    initialize = function(`type`, `name`, `uri`){
      if (!missing(`type`)) {
        stopifnot(is.character(`type`), length(`type`) == 1)
        self$`type` <- `type`
      }
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`uri`)) {
        stopifnot(is.character(`uri`), length(`uri`) == 1)
        self$`uri` <- `uri`
      }
    },
    toJSON = function() {
      AddCredentialsRequestObject <- list()
      if (!is.null(self$`type`)) {
        AddCredentialsRequestObject[['type']] <- self$`type`
      }
      if (!is.null(self$`name`)) {
        AddCredentialsRequestObject[['name']] <- self$`name`
      }
      if (!is.null(self$`uri`)) {
        AddCredentialsRequestObject[['uri']] <- self$`uri`
      }

      AddCredentialsRequestObject
    },
    fromJSON = function(AddCredentialsRequestJson) {
      AddCredentialsRequestObject <- jsonlite::fromJSON(AddCredentialsRequestJson)
      if (!is.null(AddCredentialsRequestObject$`type`)) {
        self$`type` <- AddCredentialsRequestObject$`type`
      }
      if (!is.null(AddCredentialsRequestObject$`name`)) {
        self$`name` <- AddCredentialsRequestObject$`name`
      }
      if (!is.null(AddCredentialsRequestObject$`uri`)) {
        self$`uri` <- AddCredentialsRequestObject$`uri`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "type": %s,
           "name": %s,
           "uri": %s
        }',
        self$`type`,
        self$`name`,
        self$`uri`
      )
    },
    fromJSONString = function(AddCredentialsRequestJson) {
      AddCredentialsRequestObject <- jsonlite::fromJSON(AddCredentialsRequestJson)
      self$`type` <- AddCredentialsRequestObject$`type`
      self$`name` <- AddCredentialsRequestObject$`name`
      self$`uri` <- AddCredentialsRequestObject$`uri`
    }
  )
)
