# Endpoints
#
# Endpoints API for different services in SKIL
#
# OpenAPI spec version: 1.2.0-rc1
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' FileUpload Class
#'
#' @field key 
#' @field fileName 
#' @field status 
#' @field type 
#' @field path 
#' @field fileContent 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
FileUpload <- R6::R6Class(
  'FileUpload',
  public = list(
    `key` = NULL,
    `fileName` = NULL,
    `status` = NULL,
    `type` = NULL,
    `path` = NULL,
    `fileContent` = NULL,
    initialize = function(`key`, `fileName`, `status`, `type`, `path`, `fileContent`){
      if (!missing(`key`)) {
        stopifnot(is.character(`key`), length(`key`) == 1)
        self$`key` <- `key`
      }
      if (!missing(`fileName`)) {
        stopifnot(is.character(`fileName`), length(`fileName`) == 1)
        self$`fileName` <- `fileName`
      }
      if (!missing(`status`)) {
        stopifnot(is.character(`status`), length(`status`) == 1)
        self$`status` <- `status`
      }
      if (!missing(`type`)) {
        stopifnot(is.character(`type`), length(`type`) == 1)
        self$`type` <- `type`
      }
      if (!missing(`path`)) {
        stopifnot(is.character(`path`), length(`path`) == 1)
        self$`path` <- `path`
      }
      if (!missing(`fileContent`)) {
        stopifnot(is.character(`fileContent`), length(`fileContent`) == 1)
        self$`fileContent` <- `fileContent`
      }
    },
    toJSON = function() {
      FileUploadObject <- list()
      if (!is.null(self$`key`)) {
        FileUploadObject[['key']] <- self$`key`
      }
      if (!is.null(self$`fileName`)) {
        FileUploadObject[['fileName']] <- self$`fileName`
      }
      if (!is.null(self$`status`)) {
        FileUploadObject[['status']] <- self$`status`
      }
      if (!is.null(self$`type`)) {
        FileUploadObject[['type']] <- self$`type`
      }
      if (!is.null(self$`path`)) {
        FileUploadObject[['path']] <- self$`path`
      }
      if (!is.null(self$`fileContent`)) {
        FileUploadObject[['fileContent']] <- self$`fileContent`
      }

      FileUploadObject
    },
    fromJSON = function(FileUploadJson) {
      FileUploadObject <- jsonlite::fromJSON(FileUploadJson)
      if (!is.null(FileUploadObject$`key`)) {
        self$`key` <- FileUploadObject$`key`
      }
      if (!is.null(FileUploadObject$`fileName`)) {
        self$`fileName` <- FileUploadObject$`fileName`
      }
      if (!is.null(FileUploadObject$`status`)) {
        self$`status` <- FileUploadObject$`status`
      }
      if (!is.null(FileUploadObject$`type`)) {
        self$`type` <- FileUploadObject$`type`
      }
      if (!is.null(FileUploadObject$`path`)) {
        self$`path` <- FileUploadObject$`path`
      }
      if (!is.null(FileUploadObject$`fileContent`)) {
        self$`fileContent` <- FileUploadObject$`fileContent`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "key": %s,
           "fileName": %s,
           "status": %s,
           "type": %s,
           "path": %s,
           "fileContent": %s
        }',
        self$`key`,
        self$`fileName`,
        self$`status`,
        self$`type`,
        self$`path`,
        self$`fileContent`
      )
    },
    fromJSONString = function(FileUploadJson) {
      FileUploadObject <- jsonlite::fromJSON(FileUploadJson)
      self$`key` <- FileUploadObject$`key`
      self$`fileName` <- FileUploadObject$`fileName`
      self$`status` <- FileUploadObject$`status`
      self$`type` <- FileUploadObject$`type`
      self$`path` <- FileUploadObject$`path`
      self$`fileContent` <- FileUploadObject$`fileContent`
    }
  )
)
