# Endpoints
#
# Endpoints API for different services in SKIL
#
# The version of the OpenAPI document: 1.2.2
# 
# Generated by: https://openapi-generator.tech


#' ImportModelRequest Class
#'
#' @field name 
#' @field scale 
#' @field uri 
#' @field modelType 
#' @field fileLocation 
#' @field jvmArgs 
#' @field subType 
#' @field labelsFileLocation 
#' @field extraArgs 
#' @field etlJson 
#' @field inputNames 
#' @field outputNames 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ImportModelRequest <- R6::R6Class(
  'ImportModelRequest',
  public = list(
    `name` = NULL,
    `scale` = NULL,
    `uri` = NULL,
    `modelType` = NULL,
    `fileLocation` = NULL,
    `jvmArgs` = NULL,
    `subType` = NULL,
    `labelsFileLocation` = NULL,
    `extraArgs` = NULL,
    `etlJson` = NULL,
    `inputNames` = NULL,
    `outputNames` = NULL,
    initialize = function(`name`=NULL, `scale`=NULL, `uri`=NULL, `modelType`=NULL, `fileLocation`=NULL, `jvmArgs`=NULL, `subType`=NULL, `labelsFileLocation`=NULL, `extraArgs`=NULL, `etlJson`=NULL, `inputNames`=NULL, `outputNames`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!is.null(`scale`)) {
        stopifnot(is.numeric(`scale`), length(`scale`) == 1)
        self$`scale` <- `scale`
      }
      if (!is.null(`uri`)) {
        stopifnot(is.vector(`uri`), length(`uri`) != 0)
        sapply(`uri`, function(x) stopifnot(is.character(x)))
        self$`uri` <- `uri`
      }
      if (!is.null(`modelType`)) {
        stopifnot(is.character(`modelType`), length(`modelType`) == 1)
        self$`modelType` <- `modelType`
      }
      if (!is.null(`fileLocation`)) {
        stopifnot(is.character(`fileLocation`), length(`fileLocation`) == 1)
        self$`fileLocation` <- `fileLocation`
      }
      if (!is.null(`jvmArgs`)) {
        stopifnot(is.character(`jvmArgs`), length(`jvmArgs`) == 1)
        self$`jvmArgs` <- `jvmArgs`
      }
      if (!is.null(`subType`)) {
        stopifnot(is.character(`subType`), length(`subType`) == 1)
        self$`subType` <- `subType`
      }
      if (!is.null(`labelsFileLocation`)) {
        stopifnot(is.character(`labelsFileLocation`), length(`labelsFileLocation`) == 1)
        self$`labelsFileLocation` <- `labelsFileLocation`
      }
      if (!is.null(`extraArgs`)) {
        stopifnot(is.character(`extraArgs`), length(`extraArgs`) == 1)
        self$`extraArgs` <- `extraArgs`
      }
      if (!is.null(`etlJson`)) {
        stopifnot(is.character(`etlJson`), length(`etlJson`) == 1)
        self$`etlJson` <- `etlJson`
      }
      if (!is.null(`inputNames`)) {
        stopifnot(is.vector(`inputNames`), length(`inputNames`) != 0)
        sapply(`inputNames`, function(x) stopifnot(is.character(x)))
        self$`inputNames` <- `inputNames`
      }
      if (!is.null(`outputNames`)) {
        stopifnot(is.vector(`outputNames`), length(`outputNames`) != 0)
        sapply(`outputNames`, function(x) stopifnot(is.character(x)))
        self$`outputNames` <- `outputNames`
      }
    },
    toJSON = function() {
      ImportModelRequestObject <- list()
      if (!is.null(self$`name`)) {
        ImportModelRequestObject[['name']] <-
          self$`name`
      }
      if (!is.null(self$`scale`)) {
        ImportModelRequestObject[['scale']] <-
          self$`scale`
      }
      if (!is.null(self$`uri`)) {
        ImportModelRequestObject[['uri']] <-
          self$`uri`
      }
      if (!is.null(self$`modelType`)) {
        ImportModelRequestObject[['modelType']] <-
          self$`modelType`
      }
      if (!is.null(self$`fileLocation`)) {
        ImportModelRequestObject[['fileLocation']] <-
          self$`fileLocation`
      }
      if (!is.null(self$`jvmArgs`)) {
        ImportModelRequestObject[['jvmArgs']] <-
          self$`jvmArgs`
      }
      if (!is.null(self$`subType`)) {
        ImportModelRequestObject[['subType']] <-
          self$`subType`
      }
      if (!is.null(self$`labelsFileLocation`)) {
        ImportModelRequestObject[['labelsFileLocation']] <-
          self$`labelsFileLocation`
      }
      if (!is.null(self$`extraArgs`)) {
        ImportModelRequestObject[['extraArgs']] <-
          self$`extraArgs`
      }
      if (!is.null(self$`etlJson`)) {
        ImportModelRequestObject[['etlJson']] <-
          self$`etlJson`
      }
      if (!is.null(self$`inputNames`)) {
        ImportModelRequestObject[['inputNames']] <-
          self$`inputNames`
      }
      if (!is.null(self$`outputNames`)) {
        ImportModelRequestObject[['outputNames']] <-
          self$`outputNames`
      }

      ImportModelRequestObject
    },
    fromJSON = function(ImportModelRequestJson) {
      ImportModelRequestObject <- jsonlite::fromJSON(ImportModelRequestJson)
      if (!is.null(ImportModelRequestObject$`name`)) {
        self$`name` <- ImportModelRequestObject$`name`
      }
      if (!is.null(ImportModelRequestObject$`scale`)) {
        self$`scale` <- ImportModelRequestObject$`scale`
      }
      if (!is.null(ImportModelRequestObject$`uri`)) {
        self$`uri` <- ImportModelRequestObject$`uri`
      }
      if (!is.null(ImportModelRequestObject$`modelType`)) {
        self$`modelType` <- ImportModelRequestObject$`modelType`
      }
      if (!is.null(ImportModelRequestObject$`fileLocation`)) {
        self$`fileLocation` <- ImportModelRequestObject$`fileLocation`
      }
      if (!is.null(ImportModelRequestObject$`jvmArgs`)) {
        self$`jvmArgs` <- ImportModelRequestObject$`jvmArgs`
      }
      if (!is.null(ImportModelRequestObject$`subType`)) {
        self$`subType` <- ImportModelRequestObject$`subType`
      }
      if (!is.null(ImportModelRequestObject$`labelsFileLocation`)) {
        self$`labelsFileLocation` <- ImportModelRequestObject$`labelsFileLocation`
      }
      if (!is.null(ImportModelRequestObject$`extraArgs`)) {
        self$`extraArgs` <- ImportModelRequestObject$`extraArgs`
      }
      if (!is.null(ImportModelRequestObject$`etlJson`)) {
        self$`etlJson` <- ImportModelRequestObject$`etlJson`
      }
      if (!is.null(ImportModelRequestObject$`inputNames`)) {
        self$`inputNames` <- ImportModelRequestObject$`inputNames`
      }
      if (!is.null(ImportModelRequestObject$`outputNames`)) {
        self$`outputNames` <- ImportModelRequestObject$`outputNames`
      }
    },
    toJSONString = function() {
      sprintf(
        '{
           "name":
             "%s",
           "scale":
             %d,
           "uri":
             [%s],
           "modelType":
             "%s",
           "fileLocation":
             "%s",
           "jvmArgs":
             "%s",
           "subType":
             "%s",
           "labelsFileLocation":
             "%s",
           "extraArgs":
             "%s",
           "etlJson":
             "%s",
           "inputNames":
             [%s],
           "outputNames":
             [%s]
        }',
        self$`name`,
        self$`scale`,
        paste(unlist(lapply(self$`uri`, function(x) paste0('"', x, '"'))), collapse=","),
        self$`modelType`,
        self$`fileLocation`,
        self$`jvmArgs`,
        self$`subType`,
        self$`labelsFileLocation`,
        self$`extraArgs`,
        self$`etlJson`,
        paste(unlist(lapply(self$`inputNames`, function(x) paste0('"', x, '"'))), collapse=","),
        paste(unlist(lapply(self$`outputNames`, function(x) paste0('"', x, '"'))), collapse=",")
      )
    },
    fromJSONString = function(ImportModelRequestJson) {
      ImportModelRequestObject <- jsonlite::fromJSON(ImportModelRequestJson)
      self$`name` <- ImportModelRequestObject$`name`
      self$`scale` <- ImportModelRequestObject$`scale`
      self$`uri` <- lapply(ImportModelRequestObject$`uri`, function (x) x)
      self$`modelType` <- ImportModelRequestObject$`modelType`
      self$`fileLocation` <- ImportModelRequestObject$`fileLocation`
      self$`jvmArgs` <- ImportModelRequestObject$`jvmArgs`
      self$`subType` <- ImportModelRequestObject$`subType`
      self$`labelsFileLocation` <- ImportModelRequestObject$`labelsFileLocation`
      self$`extraArgs` <- ImportModelRequestObject$`extraArgs`
      self$`etlJson` <- ImportModelRequestObject$`etlJson`
      self$`inputNames` <- lapply(ImportModelRequestObject$`inputNames`, function (x) x)
      self$`outputNames` <- lapply(ImportModelRequestObject$`outputNames`, function (x) x)
      self
    }
  )
)
