# Endpoints
#
# Endpoints API for different services in SKIL
#
# OpenAPI spec version: 1.2.0-rc1
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' ModelFeedBackRequest Class
#'
#' @field batchId 
#' @field guesses 
#' @field correct 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ModelFeedBackRequest <- R6::R6Class(
  'ModelFeedBackRequest',
  public = list(
    `batchId` = NULL,
    `guesses` = NULL,
    `correct` = NULL,
    initialize = function(`batchId`, `guesses`, `correct`){
      if (!missing(`batchId`)) {
        stopifnot(is.character(`batchId`), length(`batchId`) == 1)
        self$`batchId` <- `batchId`
      }
      if (!missing(`guesses`)) {
        stopifnot(is.list(`guesses`), length(`guesses`) != 0)
        lapply(`guesses`, function(x) stopifnot(is.character(x)))
        self$`guesses` <- `guesses`
      }
      if (!missing(`correct`)) {
        stopifnot(is.list(`correct`), length(`correct`) != 0)
        lapply(`correct`, function(x) stopifnot(is.character(x)))
        self$`correct` <- `correct`
      }
    },
    toJSON = function() {
      ModelFeedBackRequestObject <- list()
      if (!is.null(self$`batchId`)) {
        ModelFeedBackRequestObject[['batchId']] <- self$`batchId`
      }
      if (!is.null(self$`guesses`)) {
        ModelFeedBackRequestObject[['guesses']] <- self$`guesses`
      }
      if (!is.null(self$`correct`)) {
        ModelFeedBackRequestObject[['correct']] <- self$`correct`
      }

      ModelFeedBackRequestObject
    },
    fromJSON = function(ModelFeedBackRequestJson) {
      ModelFeedBackRequestObject <- jsonlite::fromJSON(ModelFeedBackRequestJson)
      if (!is.null(ModelFeedBackRequestObject$`batchId`)) {
        self$`batchId` <- ModelFeedBackRequestObject$`batchId`
      }
      if (!is.null(ModelFeedBackRequestObject$`guesses`)) {
        self$`guesses` <- ModelFeedBackRequestObject$`guesses`
      }
      if (!is.null(ModelFeedBackRequestObject$`correct`)) {
        self$`correct` <- ModelFeedBackRequestObject$`correct`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "batchId": %s,
           "guesses": [%s],
           "correct": [%s]
        }',
        self$`batchId`,
        lapply(self$`guesses`, function(x) paste(paste0('"', x, '"'), sep=",")),
        lapply(self$`correct`, function(x) paste(paste0('"', x, '"'), sep=","))
      )
    },
    fromJSONString = function(ModelFeedBackRequestJson) {
      ModelFeedBackRequestObject <- jsonlite::fromJSON(ModelFeedBackRequestJson)
      self$`batchId` <- ModelFeedBackRequestObject$`batchId`
      self$`guesses` <- ModelFeedBackRequestObject$`guesses`
      self$`correct` <- ModelFeedBackRequestObject$`correct`
    }
  )
)
