# Endpoints
#
# Endpoints API for different services in SKIL
#
# OpenAPI spec version: 1.2.0-rc1
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' RevisionsWritten Class
#'
#' @field numRevisions 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
RevisionsWritten <- R6::R6Class(
  'RevisionsWritten',
  public = list(
    `numRevisions` = NULL,
    initialize = function(`numRevisions`){
      if (!missing(`numRevisions`)) {
        stopifnot(is.numeric(`numRevisions`), length(`numRevisions`) == 1)
        self$`numRevisions` <- `numRevisions`
      }
    },
    toJSON = function() {
      RevisionsWrittenObject <- list()
      if (!is.null(self$`numRevisions`)) {
        RevisionsWrittenObject[['numRevisions']] <- self$`numRevisions`
      }

      RevisionsWrittenObject
    },
    fromJSON = function(RevisionsWrittenJson) {
      RevisionsWrittenObject <- jsonlite::fromJSON(RevisionsWrittenJson)
      if (!is.null(RevisionsWrittenObject$`numRevisions`)) {
        self$`numRevisions` <- RevisionsWrittenObject$`numRevisions`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "numRevisions": %s
        }',
        self$`numRevisions`
      )
    },
    fromJSONString = function(RevisionsWrittenJson) {
      RevisionsWrittenObject <- jsonlite::fromJSON(RevisionsWrittenJson)
      self$`numRevisions` <- RevisionsWrittenObject$`numRevisions`
    }
  )
)
