# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test NearestNeighborRequest")

model.instance <- NearestNeighborRequest$new()

test_that("k", {
  # tests for the property `k` (integer)
  # the number of results

  # uncomment below to test the property 
  #expect_equal(model.instance$`k`, "EXPECTED_RESULT")
})

test_that("inputIndex", {
  # tests for the property `inputIndex` (integer)
  # the index of the EXISTING ndarray to run a search on

  # uncomment below to test the property 
  #expect_equal(model.instance$`inputIndex`, "EXPECTED_RESULT")
})

