# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ModelStatus")

model.instance <- ModelStatus$new()

test_that("status", {
  # tests for the property `status` (integer)
  # 100 - Model set successfully. 200 - Model Updated Successfully. 201 - Model Update Failed. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`status`, "EXPECTED_RESULT")
})

