# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test RollbackStatus")

model.instance <- RollbackStatus$new()

test_that("status", {
  # tests for the property `status` (character)
  # Status of the model revision rollback.

  # uncomment below to test the property 
  #expect_equal(model.instance$`status`, "EXPECTED_RESULT")
})

