# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test LoginResponse")

model.instance <- LoginResponse$new()

test_that("token", {
  # tests for the property `token` (character)
  # Token received from the authentication server.

  # uncomment below to test the property 
  #expect_equal(model.instance$`token`, "EXPECTED_RESULT")
})

