# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test BatchCSVRecord")

model.instance <- BatchCSVRecord$new()

test_that("records", {
  # tests for the property `records` (SingleCSVRecord)

  # uncomment below to test the property 
  #expect_equal(model.instance$`records`, "EXPECTED_RESULT")
})

