/*
 * Endpoints
 * Endpoints API for different services in SKIL
 *
 * The version of the OpenAPI document: 1.2.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.skymind.skil.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * RevisionsWritten
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-06-24T15:38:03.678+08:00[Asia/Manila]")
public class RevisionsWritten {
  public static final String SERIALIZED_NAME_NUM_REVISIONS = "numRevisions";
  @SerializedName(SERIALIZED_NAME_NUM_REVISIONS)
  private Integer numRevisions;

  public RevisionsWritten numRevisions(Integer numRevisions) {
    this.numRevisions = numRevisions;
    return this;
  }

   /**
   * Get numRevisions
   * @return numRevisions
  **/
  @ApiModelProperty(value = "")
  public Integer getNumRevisions() {
    return numRevisions;
  }

  public void setNumRevisions(Integer numRevisions) {
    this.numRevisions = numRevisions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RevisionsWritten revisionsWritten = (RevisionsWritten) o;
    return Objects.equals(this.numRevisions, revisionsWritten.numRevisions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(numRevisions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RevisionsWritten {\n");
    sb.append("    numRevisions: ").append(toIndentedString(numRevisions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

