/*
 * Endpoints
 * Endpoints API for different services in SKIL
 *
 * The version of the OpenAPI document: 1.2.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.skymind.skil.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CreateJobRequest
 */
public class CreateJobRequestTest {
    private final CreateJobRequest model = new CreateJobRequest();

    /**
     * Model tests for CreateJobRequest
     */
    @Test
    public void testCreateJobRequest() {
        // TODO: test CreateJobRequest
    }

    /**
     * Test the property 'computeResourceId'
     */
    @Test
    public void computeResourceIdTest() {
        // TODO: test computeResourceId
    }

    /**
     * Test the property 'storageResourceId'
     */
    @Test
    public void storageResourceIdTest() {
        // TODO: test storageResourceId
    }

    /**
     * Test the property 'jobArgs'
     */
    @Test
    public void jobArgsTest() {
        // TODO: test jobArgs
    }

    /**
     * Test the property 'outputFileName'
     */
    @Test
    public void outputFileNameTest() {
        // TODO: test outputFileName
    }

}
