/**
 * Endpoints
 * Endpoints API for different services in SKIL
 *
 * OpenAPI spec version: 1.2.0-rc1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ai.skymind.skil.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;
import java.io.Serializable;

@ApiModel(description = "")
public class AuthPolicy implements Serializable {
  
  public enum _classEnum {
     SimpleAuthPolicy,  RoleAuthPolicy, 
  };
  @SerializedName("@class")
  private _classEnum _class = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public _classEnum getClass() {
    return _class;
  }
  public void setClass(_classEnum _class) {
    this._class = _class;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuthPolicy authPolicy = (AuthPolicy) o;
    return (this._class == null ? authPolicy._class == null : this._class.equals(authPolicy._class));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this._class == null ? 0: this._class.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuthPolicy {\n");
    
    sb.append("  _class: ").append(_class).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
