/**
 * Endpoints
 * Endpoints API for different services in SKIL
 *
 * OpenAPI spec version: 1.2.0-rc1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ai.skymind.skil.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;
import java.io.Serializable;

@ApiModel(description = "")
public class ExampleEntity implements Serializable {
  
  @SerializedName("exampleId")
  private String exampleId = null;
  @SerializedName("exampleVersion")
  private Integer exampleVersion = null;
  @SerializedName("rowNumber")
  private Integer rowNumber = null;
  @SerializedName("created")
  private Long created = null;
  @SerializedName("miniBatchId")
  private String miniBatchId = null;
  @SerializedName("miniBatchVersion")
  private Integer miniBatchVersion = null;

  /**
   * the GUID of the example
   **/
  @ApiModelProperty(value = "the GUID of the example")
  public String getExampleId() {
    return exampleId;
  }
  public void setExampleId(String exampleId) {
    this.exampleId = exampleId;
  }

  /**
   * Example version
   **/
  @ApiModelProperty(value = "Example version")
  public Integer getExampleVersion() {
    return exampleVersion;
  }
  public void setExampleVersion(Integer exampleVersion) {
    this.exampleVersion = exampleVersion;
  }

  /**
   * Row Number
   **/
  @ApiModelProperty(value = "Row Number")
  public Integer getRowNumber() {
    return rowNumber;
  }
  public void setRowNumber(Integer rowNumber) {
    this.rowNumber = rowNumber;
  }

  /**
   * when the example was created
   **/
  @ApiModelProperty(value = "when the example was created")
  public Long getCreated() {
    return created;
  }
  public void setCreated(Long created) {
    this.created = created;
  }

  /**
   * The GUID of the minibatch
   **/
  @ApiModelProperty(value = "The GUID of the minibatch")
  public String getMiniBatchId() {
    return miniBatchId;
  }
  public void setMiniBatchId(String miniBatchId) {
    this.miniBatchId = miniBatchId;
  }

  /**
   * minibatch version
   **/
  @ApiModelProperty(value = "minibatch version")
  public Integer getMiniBatchVersion() {
    return miniBatchVersion;
  }
  public void setMiniBatchVersion(Integer miniBatchVersion) {
    this.miniBatchVersion = miniBatchVersion;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExampleEntity exampleEntity = (ExampleEntity) o;
    return (this.exampleId == null ? exampleEntity.exampleId == null : this.exampleId.equals(exampleEntity.exampleId)) &&
        (this.exampleVersion == null ? exampleEntity.exampleVersion == null : this.exampleVersion.equals(exampleEntity.exampleVersion)) &&
        (this.rowNumber == null ? exampleEntity.rowNumber == null : this.rowNumber.equals(exampleEntity.rowNumber)) &&
        (this.created == null ? exampleEntity.created == null : this.created.equals(exampleEntity.created)) &&
        (this.miniBatchId == null ? exampleEntity.miniBatchId == null : this.miniBatchId.equals(exampleEntity.miniBatchId)) &&
        (this.miniBatchVersion == null ? exampleEntity.miniBatchVersion == null : this.miniBatchVersion.equals(exampleEntity.miniBatchVersion));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.exampleId == null ? 0: this.exampleId.hashCode());
    result = 31 * result + (this.exampleVersion == null ? 0: this.exampleVersion.hashCode());
    result = 31 * result + (this.rowNumber == null ? 0: this.rowNumber.hashCode());
    result = 31 * result + (this.created == null ? 0: this.created.hashCode());
    result = 31 * result + (this.miniBatchId == null ? 0: this.miniBatchId.hashCode());
    result = 31 * result + (this.miniBatchVersion == null ? 0: this.miniBatchVersion.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExampleEntity {\n");
    
    sb.append("  exampleId: ").append(exampleId).append("\n");
    sb.append("  exampleVersion: ").append(exampleVersion).append("\n");
    sb.append("  rowNumber: ").append(rowNumber).append("\n");
    sb.append("  created: ").append(created).append("\n");
    sb.append("  miniBatchId: ").append(miniBatchId).append("\n");
    sb.append("  miniBatchVersion: ").append(miniBatchVersion).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
