/* 
 * Endpoints
 *
 * Endpoints API for different services in SKIL
 *
 * OpenAPI spec version: 1.2.0-rc1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Skymind.Skil.Client.Api;
using Skymind.Skil.Client.Model;
using Skymind.Skil.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Skymind.Skil.Client.Test
{
    /// <summary>
    ///  Class for testing DeploymentObjects
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DeploymentObjectsTests
    {
        // TODO uncomment below to declare an instance variable for DeploymentObjects
        //private DeploymentObjects instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DeploymentObjects
            //instance = new DeploymentObjects();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DeploymentObjects
        /// </summary>
        [Test]
        public void DeploymentObjectsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DeploymentObjects
            //Assert.IsInstanceOfType<DeploymentObjects> (instance, "variable 'instance' is a DeploymentObjects");
        }


        /// <summary>
        /// Test the property 'Models'
        /// </summary>
        [Test]
        public void ModelsTest()
        {
            // TODO unit test for the property 'Models'
        }
        /// <summary>
        /// Test the property 'Transforms'
        /// </summary>
        [Test]
        public void TransformsTest()
        {
            // TODO unit test for the property 'Transforms'
        }
        /// <summary>
        /// Test the property 'Knn'
        /// </summary>
        [Test]
        public void KnnTest()
        {
            // TODO unit test for the property 'Knn'
        }

    }

}
