/* 
 * Endpoints
 *
 * Endpoints API for different services in SKIL
 *
 * The version of the OpenAPI document: 1.2.2
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Skymind.Skil.Client.Api;
using Skymind.Skil.Client.Model;
using Skymind.Skil.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Skymind.Skil.Client.Test
{
    /// <summary>
    ///  Class for testing DeploymentResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DeploymentResponseTests
    {
        // TODO uncomment below to declare an instance variable for DeploymentResponse
        //private DeploymentResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DeploymentResponse
            //instance = new DeploymentResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DeploymentResponse
        /// </summary>
        [Test]
        public void DeploymentResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" DeploymentResponse
            //Assert.IsInstanceOf(typeof(DeploymentResponse), instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'DeploymentSlug'
        /// </summary>
        [Test]
        public void DeploymentSlugTest()
        {
            // TODO unit test for the property 'DeploymentSlug'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Body'
        /// </summary>
        [Test]
        public void BodyTest()
        {
            // TODO unit test for the property 'Body'
        }

    }

}
