/* 
 * Endpoints
 *
 * Endpoints API for different services in SKIL
 *
 * The version of the OpenAPI document: 1.2.2
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Skymind.Skil.Client.Api;
using Skymind.Skil.Client.Model;
using Skymind.Skil.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Skymind.Skil.Client.Test
{
    /// <summary>
    ///  Class for testing JsonArrayResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class JsonArrayResponseTests
    {
        // TODO uncomment below to declare an instance variable for JsonArrayResponse
        //private JsonArrayResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of JsonArrayResponse
            //instance = new JsonArrayResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of JsonArrayResponse
        /// </summary>
        [Test]
        public void JsonArrayResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" JsonArrayResponse
            //Assert.IsInstanceOf(typeof(JsonArrayResponse), instance);
        }


        /// <summary>
        /// Test the property 'Array'
        /// </summary>
        [Test]
        public void ArrayTest()
        {
            // TODO unit test for the property 'Array'
        }

    }

}
