/* 
 * Endpoints
 *
 * Endpoints API for different services in SKIL
 *
 * The version of the OpenAPI document: 1.2.2
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Skymind.Skil.Client.Api;
using Skymind.Skil.Client.Model;
using Skymind.Skil.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Skymind.Skil.Client.Test
{
    /// <summary>
    ///  Class for testing YARNResourceDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class YARNResourceDetailsTests
    {
        // TODO uncomment below to declare an instance variable for YARNResourceDetails
        //private YARNResourceDetails instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of YARNResourceDetails
            //instance = new YARNResourceDetails();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of YARNResourceDetails
        /// </summary>
        [Test]
        public void YARNResourceDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" YARNResourceDetails
            //Assert.IsInstanceOf(typeof(YARNResourceDetails), instance);
        }


        /// <summary>
        /// Test the property 'Class'
        /// </summary>
        [Test]
        public void ClassTest()
        {
            // TODO unit test for the property 'Class'
        }
        /// <summary>
        /// Test the property 'ResourceId'
        /// </summary>
        [Test]
        public void ResourceIdTest()
        {
            // TODO unit test for the property 'ResourceId'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'SubType'
        /// </summary>
        [Test]
        public void SubTypeTest()
        {
            // TODO unit test for the property 'SubType'
        }
        /// <summary>
        /// Test the property 'LocalSparkHome'
        /// </summary>
        [Test]
        public void LocalSparkHomeTest()
        {
            // TODO unit test for the property 'LocalSparkHome'
        }

    }

}
