/*
 * Endpoints
 *
 * Endpoints API for different services in SKIL
 *
 * The version of the OpenAPI document: 1.2.2
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;


#[derive(Debug, Serialize, Deserialize)]
pub struct CreateJobRequest {
    /// Compute resource ID
    #[serde(rename = "computeResourceId", skip_serializing_if = "Option::is_none")]
    pub compute_resource_id: Option<i64>,
    /// Storage resource ID
    #[serde(rename = "storageResourceId", skip_serializing_if = "Option::is_none")]
    pub storage_resource_id: Option<i64>,
    /// Job arguments
    #[serde(rename = "jobArgs", skip_serializing_if = "Option::is_none")]
    pub job_args: Option<String>,
    /// Output file name
    #[serde(rename = "outputFileName", skip_serializing_if = "Option::is_none")]
    pub output_file_name: Option<String>,
}

impl CreateJobRequest {
    pub fn new() -> CreateJobRequest {
        CreateJobRequest {
            compute_resource_id: None,
            storage_resource_id: None,
            job_args: None,
            output_file_name: None,
        }
    }
}


