mod add_credentials_request;
pub use self::add_credentials_request::AddCredentialsRequest;
mod add_example_request;
pub use self::add_example_request::AddExampleRequest;
mod add_model_history_request;
pub use self::add_model_history_request::AddModelHistoryRequest;
mod add_resource_request;
pub use self::add_resource_request::AddResourceRequest;
mod aggregate_prediction;
pub use self::aggregate_prediction::AggregatePrediction;
mod azure_storage_resource_details;
pub use self::azure_storage_resource_details::AzureStorageResourceDetails;
mod base64_nd_array_body;
pub use self::base64_nd_array_body::Base64NdArrayBody;
mod base64_nd_array_body_knn;
pub use self::base64_nd_array_body_knn::Base64NdArrayBodyKnn;
mod batch_csv_record;
pub use self::batch_csv_record::BatchCsvRecord;
mod batch_image_record;
pub use self::batch_image_record::BatchImageRecord;
mod best_model;
pub use self::best_model::BestModel;
mod classification_result;
pub use self::classification_result::ClassificationResult;
mod create_deployment_request;
pub use self::create_deployment_request::CreateDeploymentRequest;
mod create_job_request;
pub use self::create_job_request::CreateJobRequest;
mod credentials;
pub use self::credentials::Credentials;
mod data_proc_resource_details;
pub use self::data_proc_resource_details::DataProcResourceDetails;
mod deployment_objects;
pub use self::deployment_objects::DeploymentObjects;
mod deployment_response;
pub use self::deployment_response::DeploymentResponse;
mod detected_object;
pub use self::detected_object::DetectedObject;
mod detection_result;
pub use self::detection_result::DetectionResult;
mod download_output_file_request;
pub use self::download_output_file_request::DownloadOutputFileRequest;
mod emr_resource_details;
pub use self::emr_resource_details::EmrResourceDetails;
mod evaluation_results_entity;
pub use self::evaluation_results_entity::EvaluationResultsEntity;
mod example_entity;
pub use self::example_entity::ExampleEntity;
mod experiment_entity;
pub use self::experiment_entity::ExperimentEntity;
mod file_upload;
pub use self::file_upload::FileUpload;
mod file_upload_list;
pub use self::file_upload_list::FileUploadList;
mod google_storage_resource_details;
pub use self::google_storage_resource_details::GoogleStorageResourceDetails;
mod hd_insight_resource_details;
pub use self::hd_insight_resource_details::HdInsightResourceDetails;
mod hdfs_resource_details;
pub use self::hdfs_resource_details::HdfsResourceDetails;
mod image_transform_process;
pub use self::image_transform_process::ImageTransformProcess;
mod import_model_request;
pub use self::import_model_request::ImportModelRequest;
mod ind_array;
pub use self::ind_array::IndArray;
mod inline_response_200;
pub use self::inline_response_200::InlineResponse200;
mod job_entity;
pub use self::job_entity::JobEntity;
mod json_array_response;
pub use self::json_array_response::JsonArrayResponse;
mod log_batch;
pub use self::log_batch::LogBatch;
mod log_request;
pub use self::log_request::LogRequest;
mod meta_data;
pub use self::meta_data::MetaData;
mod minibatch_entity;
pub use self::minibatch_entity::MinibatchEntity;
mod model_entity;
pub use self::model_entity::ModelEntity;
mod model_feed_back_request;
pub use self::model_feed_back_request::ModelFeedBackRequest;
mod model_history_entity;
pub use self::model_history_entity::ModelHistoryEntity;
mod model_instance_entity;
pub use self::model_instance_entity::ModelInstanceEntity;
mod model_response;
pub use self::model_response::ModelResponse;
mod model_status;
pub use self::model_status::ModelStatus;
mod multi_class_classification_result;
pub use self::multi_class_classification_result::MultiClassClassificationResult;
mod multi_predict_request;
pub use self::multi_predict_request::MultiPredictRequest;
mod multi_predict_response;
pub use self::multi_predict_response::MultiPredictResponse;
mod nearest_neighbor_request;
pub use self::nearest_neighbor_request::NearestNeighborRequest;
mod nearest_neighbors_result;
pub use self::nearest_neighbors_result::NearestNeighborsResult;
mod nearest_neighbors_results;
pub use self::nearest_neighbors_results::NearestNeighborsResults;
mod new_deployment;
pub use self::new_deployment::NewDeployment;
mod prediction;
pub use self::prediction::Prediction;
mod resource;
pub use self::resource::Resource;
mod resource_credentials;
pub use self::resource_credentials::ResourceCredentials;
mod resource_group;
pub use self::resource_group::ResourceGroup;
mod s3_resource_details;
pub use self::s3_resource_details::S3ResourceDetails;
mod set_state;
pub use self::set_state::SetState;
mod single_csv_record;
pub use self::single_csv_record::SingleCsvRecord;
mod single_image_record;
pub use self::single_image_record::SingleImageRecord;
mod token;
pub use self::token::Token;
mod transform_process;
pub use self::transform_process::TransformProcess;
mod update_best_model;
pub use self::update_best_model::UpdateBestModel;
mod yarn_resource_details;
pub use self::yarn_resource_details::YarnResourceDetails;

// TODO(farcaller): sort out files
pub struct File;
