/*
 * Endpoints
 *
 * Endpoints API for different services in SKIL
 *
 * API version: 1.2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package skilclient

type MultiPredictRequest struct {
	Id string `json:"id,omitempty"`
	NeedsPreProcessing bool `json:"needsPreProcessing,omitempty"`
	Inputs []IndArray `json:"inputs,omitempty"`
	InputMasks []IndArray `json:"inputMasks,omitempty"`
}
