/*
 * Endpoints
 *
 * Endpoints API for different services in SKIL
 *
 * API version: 1.2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package skilclient

type ImportModelRequest struct {
	Name string `json:"name,omitempty"`
	Scale int32 `json:"scale,omitempty"`
	Uri []string `json:"uri,omitempty"`
	ModelType string `json:"modelType,omitempty"`
	FileLocation string `json:"fileLocation,omitempty"`
	JvmArgs string `json:"jvmArgs,omitempty"`
	SubType string `json:"subType,omitempty"`
	LabelsFileLocation string `json:"labelsFileLocation,omitempty"`
	ExtraArgs string `json:"extraArgs,omitempty"`
	EtlJson string `json:"etlJson,omitempty"`
	InputNames []string `json:"inputNames,omitempty"`
	OutputNames []string `json:"outputNames,omitempty"`
}
