//
// EvaluationResultsEntity.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class EvaluationResultsEntity: JSONEncodable {

    public var evaluation: String?
    public var evalName: String?
    public var modelInstanceId: String?
    /** When the evaluation result was created */
    public var created: Int64?
    public var f1: Double?
    public var precision: Double?
    public var recall: Double?
    public var accuracy: Double?
    public var rmse: Double?
    public var auc: Double?
    public var meanAbsoluteError: Double?
    public var meanRelativeError: Double?
    public var r2: Double?
    /** GUID of the evaluation */
    public var evalId: String?
    public var evalVersion: Int32?
    public var binaryThreshold: Double?
    public var binaryThresholds: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["evaluation"] = self.evaluation
        nillableDictionary["evalName"] = self.evalName
        nillableDictionary["modelInstanceId"] = self.modelInstanceId
        nillableDictionary["created"] = self.created?.encodeToJSON()
        nillableDictionary["f1"] = self.f1
        nillableDictionary["precision"] = self.precision
        nillableDictionary["recall"] = self.recall
        nillableDictionary["accuracy"] = self.accuracy
        nillableDictionary["rmse"] = self.rmse
        nillableDictionary["auc"] = self.auc
        nillableDictionary["meanAbsoluteError"] = self.meanAbsoluteError
        nillableDictionary["meanRelativeError"] = self.meanRelativeError
        nillableDictionary["r2"] = self.r2
        nillableDictionary["evalId"] = self.evalId
        nillableDictionary["evalVersion"] = self.evalVersion?.encodeToJSON()
        nillableDictionary["binaryThreshold"] = self.binaryThreshold
        nillableDictionary["binaryThresholds"] = self.binaryThresholds

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

