//
// ResourceGroup.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class ResourceGroup: JSONEncodable {

    /** ID of the resource group */
    public var groupId: Int64?
    /** Name of the resource group */
    public var groupName: String?
    /** Milliseconds in Long when the resource group was added */
    public var added: Int64?
    /** Milliseconds in Long when the resource group was updated */
    public var updated: Int64?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["groupId"] = self.groupId?.encodeToJSON()
        nillableDictionary["groupName"] = self.groupName
        nillableDictionary["added"] = self.added?.encodeToJSON()
        nillableDictionary["updated"] = self.updated?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

